version: "3.7"
services:
    mysql:
        container_name: mysql
        image: mysql:latest
        restart: always
        expose:
            - 3306
        environment: 
            MYSQL_DATABASE: test
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: 1qaz@WSX
        volumes:
            - ./migration/init.sql:/docker-entrypoint-initdb.d/init.sql

    shopping:
        container_name: shopping
        image: shopping:latest
        restart: always
        build: .
        ports:
            - 8080:8080
        environment:
            DB_Dialect: mysql
            DB_Host: mysql
            DB_Port: 3306
            DB_Name: test
            DB_User: root
            DB_Password: 1qaz@WSX
        depends_on:
            - mysql
